namespace igLibrary.Gen.MetaEnum;

public enum ECollectibleType
{
	eCT_Invalid = 0,
	eCT_Begin = 1,
	eCT_Area = 1,
	eCT_Butterfly = 2,
	eCT_Charm = 3,
	eCT_Hat = 4,
	eCT_Health = 5,
	eCT_LegendaryTreasure = 6,
	eCT_LevelSpecific = 7,
	eCT_Map = 8,
	eCT_Money = 9,
	eCT_SoulGem = 10,
	eCT_StoryScroll = 11,
	eCT_TreasureChest = 12,
	eCT_Xp = 13,
	eCT_HeroicChallengeDual = 14,
	eCT_PowerUp = 15,
	eCT_Skylander = 16,
	eCT_Vehicle = 17,
	eCT_MagicItem = 18,
	eCT_Pet = 19,
	eCT_Expansion_2011 = 20,
	eCT_Expansion_2013 = 21,
	eCT_Expansion_2015 = 22,
	eCT_TurboZone = 23,
	eCT_Arena = 24,
	eCT_Mod = 25,
	eCT_VehicleBlueprint = 26,
	eCT_VehicleXp = 27,
	eCT_VehicleShields = 28,
	eCT_Pinata = 29,
	eCT_Stardust = 30,
	eCT_SkystonesSmashCard = 31,
	eCT_ContentBundle = 32,
	eCT_Theater = 33,
	eCT_SkylanderStat = 34,
	eCT_VehicleStat = 35,
	eCT_CrystalTrap = 36,
	eCT_LevelUpOrb = 37,
	eCT_Max = 38
}
