namespace igLibrary.Gen.MetaEnum;

public enum EController
{
	ECONTROLLER_NONE = -1,
	ECONTROLLER_ONE,
	ECONTROLLER_TWO,
	ECONTROLLER_THREE,
	ECONTROLLER_FOUR,
	ECONTROLLER_FIVE,
	ECONTROLLER_SIX,
	ECONTROLLER_SEVEN,
	ECONTROLLER_EIGHT,
	ECONTROLLER_MAX
}
