namespace igLibrary.Gen.MetaEnum;

public enum EControllerType
{
	ECONTROLLERTYPE_INVALID,
	ECONTROLLERTYPE_XENON,
	ECONTROLLERTYPE_PS3,
	ECONTROLLERTYPE_CAFE_DRC,
	ECONTROLLERTYPE_CAFE_PRO,
	ECONTROLLERTYPE_CAFE_WIIMOTE,
	ECONTROLLERTYPE_CAFE_CLASSIC,
	ECONTROLLERTYPE_WII_WIIMOTE,
	ECONTROLLERTYPE_WII_CLASSIC,
	ECONTROLLERTYPE_DURANGO,
	ECONTROLLERTYPE_PS4,
	ECONTROLLERTYPE_ASPEN,
	ECONTROLLERTYPE_ASPEN_VIRTUAL
}
