namespace igLibrary.Gen.MetaEnum;

public enum EGearBitsMessageType
{
	eGBMT_START_GUNS,
	eGBMT_STOP_GUNS,
	eGBMT_PULSE_PART,
	eGBMT_BOOSTERS_ON,
	eGBMT_BOOSTERS_OFF,
	eGBMT_WEAPON_LIGHTPATTERN,
	eGBMT_KIT_LIGHTPATTERN,
	eGBMT_VOICE_LIGHTPATTERN,
	eGBMT_STOP_LIGHTPATTERN
}
