namespace igLibrary.Gen.MetaEnum;

public enum ESaveState
{
	STATE_IDLE,
	STATE_WAITING_FOR_DIALOG,
	STATE_SHOW_SAVE_DIALOG_FOR_MINIMUM_TIME_POST_SAVE,
	STATE_CHECK_PROFILE,
	STATE_SELECT_DEVICE,
	STATE_SCAN_DEVICE,
	STATE_SCAN_DEVICE_PENDING,
	STATE_LOAD_SLOTS_AND_OPTIONS,
	STATE_LOAD_SLOTS_AND_OPTIONS_PENDING,
	STATE_SAVE_OPTIONS,
	STATE_SAVE_OPTIONS_PENDING,
	STATE_WRITE_FILE,
	STATE_WRITE_FILE_PENDING,
	STATE_READ_FILE,
	STATE_READ_FILE_PENDING,
	STATE_VERIFY_SPACE_FOR_NEWGAME,
	STATE_DELETE_SLOT,
	STATE_DELETE_SLOT_PENDING,
	STATE_DELETE_OPTIONS,
	STATE_DELETE_OPTIONS_PENDING
}
