namespace igLibrary.Gen.MetaEnum;

public enum ESaveLoad
{
	SL_IDLE,
	SL_SAVE_OPTIONS,
	SL_LOAD_SLOTS_AND_OPTIONS,
	SL_VERIFY_SPACE_FOR_NEWGAME,
	SL_LOAD_GAME,
	SL_SAVE_GAME,
	SL_DELETE_GAME,
	SL_DELETE_OPTIONS
}
