namespace igLibrary.Gen.MetaEnum;

public enum EVehicleId
{
	EVEHICLEID_NONE = -1,
	EVEHICLEID_ONE,
	EVEHICLEID_TWO,
	EVEHICLEID_THREE,
	EVEHICLEID_FOUR,
	EVEHICLEID_FIVE,
	EVEHICLEID_SIX,
	EVEHICLEID_SEVEN,
	EVEHICLEID_EIGHT,
	EVEHICLEID_MAX
}
