namespace igLibrary.Gen.MetaEnum;

public enum IG_CORE_LANGUAGE
{
	IG_CORE_LANGUAGE_FIRST = 0,
	IG_CORE_LANGUAGE_ARABIC = 0,
	IG_CORE_LANGUAGE_BULGARIAN = 1,
	IG_CORE_LANGUAGE_CHINESE = 2,
	IG_CORE_LANGUAGE_CZECH = 3,
	IG_CORE_LANGUAGE_DANISH = 4,
	IG_CORE_LANGUAGE_DUTCH = 5,
	IG_CORE_LANGUAGE_ENGLISH = 6,
	IG_CORE_LANGUAGE_FINNISH = 7,
	IG_CORE_LANGUAGE_FRENCH = 8,
	IG_CORE_LANGUAGE_GERMAN = 9,
	IG_CORE_LANGUAGE_GREEK = 10,
	IG_CORE_LANGUAGE_HEBREW = 11,
	IG_CORE_LANGUAGE_HINDI = 12,
	IG_CORE_LANGUAGE_HUNGARIAN = 13,
	IG_CORE_LANGUAGE_ITALIAN = 14,
	IG_CORE_LANGUAGE_JAPANESE = 15,
	IG_CORE_LANGUAGE_KOREAN = 16,
	IG_CORE_LANGUAGE_NORWEGIAN = 17,
	IG_CORE_LANGUAGE_POLISH = 18,
	IG_CORE_LANGUAGE_PORTUGUESE = 19,
	IG_CORE_LANGUAGE_RUSSIAN = 20,
	IG_CORE_LANGUAGE_SPANISH = 21,
	IG_CORE_LANGUAGE_SPANISH_MEXICAN = 22,
	IG_CORE_LANGUAGE_SWEDISH = 23,
	IG_CORE_LANGUAGE_TAIWANESE = 24,
	IG_CORE_LANGUAGE_TURKISH = 25,
	IG_CORE_LANGUAGE_LAST = 25
}
