namespace igLibrary.Gen.MetaEnum;

public enum IG_CORE_DEVICE_CLASS
{
	IG_CORE_DEVICE_CLASS_CONSOLE_GEN8 = 1,
	IG_CORE_DEVICE_CLASS_CONSOLE_GEN7 = 2,
	IG_CORE_DEVICE_CLASS_MOBILE_HIGH = 4,
	IG_CORE_DEVICE_CLASS_MOBILE_MEDIUM = 8,
	IG_CORE_DEVICE_CLASS_MOBILE_LOW = 16,
	IG_CORE_DEVICE_CLASS_NONE = 0
}
