namespace igLibrary.Gen.MetaEnum;

public enum IG_GFX_ALPHA_FUNCTION
{
	IG_GFX_ALPHA_FUNCTION_NEVER,
	IG_GFX_ALPHA_FUNCTION_LESS,
	IG_GFX_ALPHA_FUNCTION_EQUAL,
	IG_GFX_ALPHA_FUNCTION_LEQUAL,
	IG_GFX_ALPHA_FUNCTION_GREATER,
	IG_GFX_ALPHA_FUNCTION_NOTEQUAL,
	IG_GFX_ALPHA_FUNCTION_GEQUAL,
	IG_GFX_ALPHA_FUNCTION_ALWAYS
}
