namespace igLibrary.Gen.MetaEnum;

public enum IG_GFX_TEXTURE_WRAP
{
	IG_GFX_TEXTURE_WRAP_CLAMP,
	IG_GFX_TEXTURE_WRAP_REPEAT,
	IG_GFX_TEXTURE_WRAP_REGION_CLAMP,
	IG_GFX_TEXTURE_WRAP_REGION_REPEAT,
	IG_GFX_TEXTURE_WRAP_BORDER
}
