namespace igLibrary.Gen.MetaEnum;

public enum IG_GFX_TEXTURE_FILTER
{
	IG_GFX_TEXTURE_FILTER_NEAREST = 0,
	IG_GFX_TEXTURE_FILTER_NEAREST_MIPMAP_NONE = 0,
	IG_GFX_TEXTURE_FILTER_LINEAR = 1,
	IG_GFX_TEXTURE_FILTER_LINEAR_MIPMAP_NONE = 1,
	IG_GFX_TEXTURE_FILTER_NEAREST_MIPMAP_NEAREST = 2,
	IG_GFX_TEXTURE_FILTER_NEAREST_MIPMAP_LINEAR = 3,
	IG_GFX_TEXTURE_FILTER_LINEAR_MIPMAP_NEAREST = 4,
	IG_GFX_TEXTURE_FILTER_LINEAR_MIPMAP_LINEAR = 5,
	IG_GFX_TEXTURE_FILTER_ANISOTROPIC = 6,
	IG_GFX_TEXTURE_FILTER_ANISOTROPIC_MIPMAP_NONE = 6,
	IG_GFX_TEXTURE_FILTER_ANISOTROPIC_MIPMAP_NEAREST = 7,
	IG_GFX_TEXTURE_FILTER_ANISOTROPIC_MIPMAP_LINEAR = 8
}
