namespace igLibrary.Gen.MetaEnum;

public enum IG_GFX_STENCIL_OPERATION
{
	IG_GFX_STENCIL_OPERATION_KEEP,
	IG_GFX_STENCIL_OPERATION_ZERO,
	IG_GFX_STENCIL_OPERATION_REPLACE,
	IG_GFX_STENCIL_OPERATION_INCR,
	IG_GFX_STENCIL_OPERATION_INCR_WRAP,
	IG_GFX_STENCIL_OPERATION_DECR,
	IG_GFX_STENCIL_OPERATION_DECR_WRAP,
	IG_GFX_STENCIL_OPERATION_INVERT
}
