namespace igLibrary.Gen.MetaEnum;

public enum IG_GFX_BLENDING_EQUATION
{
	IG_GFX_BLENDING_EQUATION_ADD,
	IG_GFX_BLENDING_EQUATION_SUBTRACT,
	IG_GFX_BLENDING_EQUATION_REVERSE_SUBTRACT,
	IG_GFX_BLENDING_EQUATION_MIN,
	IG_GFX_BLENDING_EQUATION_MAX
}
