namespace igLibrary.Gen.MetaEnum;

public enum IG_MATH_COLORSPACE_FORMAT
{
	IG_MATH_COLORSPACE_FORMAT_ABGR,
	IG_MATH_COLORSPACE_FORMAT_RGBA,
	IG_MATH_COLORSPACE_FORMAT_ARGB,
	IG_MATH_COLORSPACE_FORMAT_BGR,
	IG_MATH_COLORSPACE_FORMAT_RGB,
	IG_MATH_COLORSPACE_FORMAT_HSV,
	IG_MATH_COLORSPACE_FORMAT_BGRA
}
