namespace igLibrary.Gen.MetaEnum;

public enum IG_MATH_SPATIAL_REGION
{
	IG_MATH_SPATIAL_REGION_XP_YP_ZP,
	IG_MATH_SPATIAL_REGION_XP_YP_ZN,
	IG_MATH_SPATIAL_REGION_XP_YN_ZP,
	IG_MATH_SPATIAL_REGION_XP_YN_ZN,
	IG_MATH_SPATIAL_REGION_XN_YP_ZP,
	IG_MATH_SPATIAL_REGION_XN_YP_ZN,
	IG_MATH_SPATIAL_REGION_XN_YN_ZP,
	IG_MATH_SPATIAL_REGION_XN_YN_ZN
}
