# This workflow will build a .NET project and publish it as a release.
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    - name: Publish build artifacts
      if: success()
      run: dotnet publish -c Release -o ./artifacts
    
    - name: Publish build artifacts
      if: success()
      run: dotnet publish -c Release -o ./artifacts

    - name: Archive build artifacts
      if: success()
      run: zip -r igModelTool.zip ./artifacts/*

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: igModelTool
        path: igModelTool.zip
    
